; This is a dummy lein project for using nrepl, vimclojure, etc.
(defproject hystrix-clj "0.0.0"
  :description ""
  :url ""
  :license {:name ""
            :url "http://netflix.com"}

  ; No dependencies here because we rely on Ivy and the :resoure-paths hack below
  :dependencies []
  :warn-on-reflection true

  :profiles {
    :dev {
      :jvm-opts [ ]
      :source-paths ["src/main/clojure" "src/test/clojure"]

      ; runtimeClasspath is generated by build.gradle
      :resource-paths ~(-> "runtimeClasspath"
                         slurp
                         (.split ":")
                         vec) }})

